### ISSUE TITLE
Content/Tagging Cycling Packages (none returned)

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#359]
- Tags Searched: **Cykling**
- Page URL: http://inspirationalsearch.spies.dk/isearch/prod/

### Screen Shot

![any chrome any cyklingarticle_07_article_tag_added](https://cloud.githubusercontent.com/assets/194400/16584011/26282bd2-42b1-11e6-89f6-64397a7b4f94.png)

### Expected Behaviour

I expect to see packages returned when I search for Cykling

### Actual Behaviour

Only articles are displayed.

### Debug Information

- Logs ID: https://search-isearch-monitoring-twv4p4ddtbyezpwikubk4j4uoe.eu-west-1.es.amazonaws.com/_plugin/kibana/#/discover/Traceable-ID-Search?_g=()&_a=(columns:!(msg,traceable_id,name),filters:!(),index:'*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'-@message:%22$START%22%20AND%20-@message:%22$END%22%20AND%20-@message:%22$REPORT%22%20traceable_id:%225f2c53d9-74ae-419d-8fa1-220c46ee332a%22')),sort:!('@timestamp',desc))
- Tracey ID: http://numo-tracey.s3-website-eu-west-1.amazonaws.com/#/cfa1b880-42a8-11e6-af94-d1e563f885bb

### Further Information

This is a "_content_" problem, not a `code` issue. but we need _somewhere_ to record work done to _resolve_ it.

**Comment by nelsonic** [comment]
When I added the Mallorca Cycling tag a package was returned:
![tc-isearch-cycling-with-pacakge-result](https://cloud.githubusercontent.com/assets/194400/16592110/0dc1e922-42d7-11e6-8842-83d2a5ff1b7c.png)

The issue is _availability_ ...

**Comment by tomgco** [comment]
Who is working on content management?

**Comment by nelsonic** [comment]
@tomgco good question. It was _meant_ to be looked by our friends in Stockholm, but I don't think they have it high on their Todo list...

**Comment by emiledskar** [comment]
@nelsonic @tomgco: Rasmus & Martin in Denmark are working with content management. Seems reasonable that they do it because they have better understanding of what should be linked and not.

On the issue: I have tried to add the outgoing link "Playa de Palma" which is a geo tag but when I save all the other tags disappears. I have tried multiple times and I can not get "Playa de Palma" to be saved as outgoing with the cykling articles.

Not sure if I'm using taggable UI wrong
