### ISSUE TITLE
Dropdown should remain open when focus is set to the input field

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#489]
Not sure if any of these are fixed in #477 but this is what I can see on v 1.1.0

### Expected Behaviour
The dropdown should remain open when focus is set to the input field

### Actual Behaviour
- [x] Pressing enter when focus is set to the input field will close the dropdown.
In this video I click enter after I have typed London.
[link](https://drive.google.com/open?id=0BwJ2qQvXEjayUENKNzNLR1hzYUU)

- [ ] Removing all text fast with backspace closes the dropdown.
[link](https://drive.google.com/open?id=0BwJ2qQvXEjaybkFoWS1NVnB2TjA)

- [ ] Sometimes the dropdown disappears when typing.
[link](https://drive.google.com/open?id=0BwJ2qQvXEjayak1UQkJDaGV1Tkk)

**Comment by tomgco** [comment]
> Pressing enter when focus is set to the input field will close the dropdown.
> In this video I click enter after I have typed London.
> link

Confirmed in v1.1.0

> Removing all text fast with backspace closes the dropdown.
> link

Confirmed in v1.1.0

> Sometimes the dropdown disappears when typing.
> link

Confirmed in v1.1.0

**Comment by Kumjami** [comment]
> Pressing enter when focus is set to the input field will close the dropdown.
In this video I click enter after I have typed London.


Updating the component this has been fixed. Actually, right now the first suggestion will be automatically selected while typing. 
 
> Sometimes the dropdown disappears when typing.

This is also suppose to be fixed with the last update of the Autosuggest component ([see releases](https://github.com/moroshko/react-autosuggest/releases))


>Removing all text fast with backspace closes the dropdown.

Working on it.
